{
 "title": "ContinuousRestorePlan Detail",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "loki", "query": "loki" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "label_values({transaction_type=\"ContinuousRestorePlan\",transaction_resource_name=~\"$ContinuousRestorePlan\"}, service_type)"
   },
   {
    "name": "ContinuousRestorePlan",
    "label": "ContinuousRestorePlan",
    "query": {
     "query": "trilio_continuousrestoreplan_info{cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> ContinuousRestorePlan Detail </h1></center>"
   }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_continuousrestoreplan_info{continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "title": "Source BackupPlan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_continuousrestoreplan_info{ continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "title": "Source Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_continuousrestoreplan_info{ continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "title": "Num of ConsistentSets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_continuousrestoreplan_info{ continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "title": "ContinuousRestorePolicy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_continuousrestoreplan_info{ continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_continuousrestoreplan_info{ continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "title": "ConsistentSets",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "trilio_consistentset_info{continuousrestoreplan=~\"$ContinuousRestorePlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ConsistentSet\"}"
    }
   ]
  },
  {
   "title": "ContinuousRestorePlan Logs",
   "type": "logs",
   "description": "ContinuousRestorePlan Logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "{transaction_type=\"ContinuousRestorePlan\",transaction_resource_name=~\"$ContinuousRestorePlan\",service_type=~\"$service_type\"}"
    }
   ]
  }
 ]
}