{
 "title": "Restore Detail",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "loki", "query": "loki" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Restore",
    "label": "Restore",
    "query": {
     "query": "trilio_restore_info{cluster=~\"$Cluster\",kind=\"Restore\"}"
    }
   },
   {
    "name": "Namespace",
    "label": "Restore Namespace",
    "query": "label_values({transaction_type=~\"Restore\",transaction_resource_name=~\"$Restore\"},transaction_resource_namespace)"
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "label_values({transaction_type=\"Restore\",transaction_resource_name=~\"$Restore\"}, service_type)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> Restore Detail </h1></center>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "trilio_restore_status_percentage{restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"Restore\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 7, "y": 2 } },
  {
   "title": "Metadata Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "avg(trilio_restore_metadata_info{restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"Restore\"}) by (objecttype, applicationtype)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_restore_info{restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"Restore\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_restore_info{ restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_restore_info{ restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "trilio_restore_info{ restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"Restore\"}"
    }
   ]
  },
  {
   "title": "Restore Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{transaction_type=\"Restore\",transaction_resource_name=~\"$Restore\",service_type=~\"$service_type\"}"
    }
   ]
  }
 ]
}